// AUTO-GENERATED by build.mjs -- do not edit by hand. Regenerated on every build.
const BotVersion = {
  version: "1.4.3-beta",
  description: "Fix diagnostic clipboard recursion soften sustain HP-drop confirmation and add Archer Sniper Shot finisher",
  builtAt: "2026-06-29T11:08:49.652Z"
};
