import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Command line arguments parsing
const args = process.argv.slice(2);
let noBump = false;
let description = '';
let setVersion = '';

for (let i = 0; i < args.length; i++) {
  const arg = args[i].toLowerCase();
  if (arg === '--nobump' || arg === '-nobump') {
    noBump = true;
  } else if ((arg === '--desc' || arg === '-desc') && args[i + 1]) {
    description = args[++i];
  } else if ((arg === '--setversion' || arg === '-setversion') && args[i + 1]) {
    setVersion = args[++i];
  }
}

const modulesDir = path.join(__dirname, 'modules');
const versionFile = path.join(__dirname, 'version.json');
const bundleFile = path.join(__dirname, 'rebuilt_bot.user.js');
const versionModuleFile = path.join(modulesDir, '05-version.js');
const skillDbFile = path.join(__dirname, 'data', 'ligmar_hero_skills_db.json');
const skillMasterModuleFile = path.join(modulesDir, '87-skill-master.generated.js');

function splitSemVer(v) {
  const m = v.match(/^(\d+)\.(\d+)\.(\d+)(?:-([0-9A-Za-z][0-9A-Za-z.-]*))?$/);
  if (!m) {
    throw new Error(`Invalid semver: ${v}`);
  }
  return {
    major: parseInt(m[1], 10),
    minor: parseInt(m[2], 10),
    patch: parseInt(m[3], 10),
    prerelease: m[4] || ''
  };
}

function formatSemVer(parsed, patchOverride) {
  const patch = patchOverride !== undefined ? patchOverride : parsed.patch;
  let out = `${parsed.major}.${parsed.minor}.${patch}`;
  if (parsed.prerelease) {
    out += `-${parsed.prerelease}`;
  }
  return out;
}

// 1. Load version state
let versionState = JSON.parse(fs.readFileSync(versionFile, 'utf8').trim().replace(/^\uFEFF/, ''));

// 2. Handle Version Bump
if (!noBump) {
  if (!description) {
    console.error('Error: Description is required for a version bump. Use: node build.mjs --desc "short summary" OR node build.mjs --nobump');
    process.exit(1);
  }

  let newVersion;
  if (setVersion) {
    const parsedSet = splitSemVer(setVersion.trim());
    newVersion = formatSemVer(parsedSet, parsedSet.patch);
  } else {
    const parsed = splitSemVer(versionState.version);
    newVersion = formatSemVer(parsed, parsed.patch + 1);
  }

  const now = new Date().toISOString();
  const entry = {
    version: newVersion,
    description: description,
    date: now
  };

  let historyList = Array.isArray(versionState.history) ? versionState.history : [];
  historyList.unshift(entry);
  if (historyList.length > 50) {
    historyList = historyList.slice(0, 50);
  }

  versionState = {
    version: newVersion,
    description: description,
    builtAt: now,
    history: historyList
  };

  fs.writeFileSync(versionFile, JSON.stringify(versionState, null, 2), 'utf8');
}

const activeVersion = versionState.version;
const activeDescription = versionState.description;
const activeBuiltAt = versionState.builtAt;

// Ensure modules folder exists
if (!fs.existsSync(modulesDir)) {
  fs.mkdirSync(modulesDir, { recursive: true });
}

// 3. Regenerate 05-version.js
const versionModuleContent = `// AUTO-GENERATED by build.mjs -- do not edit by hand. Regenerated on every build.
const BotVersion = {
  version: ${JSON.stringify(activeVersion)},
  description: ${JSON.stringify(activeDescription)},
  builtAt: ${JSON.stringify(activeBuiltAt)}
};
`;
fs.writeFileSync(versionModuleFile, versionModuleContent, 'utf8');

// 4. Generate 87-skill-master.generated.js
if (fs.existsSync(skillDbFile)) {
  const skillDbRaw = fs.readFileSync(skillDbFile, 'utf8').trim().replace(/^\uFEFF/, '');
  const skillMasterContent = `// AUTO-GENERATED by build.mjs -- do not edit by hand. Regenerated on every build.
const SkillMasterDb = JSON.parse(${JSON.stringify(skillDbRaw)});

function buildSkillMasterIndex() {
  const byClass = {};
  const keys = Object.keys(SkillMasterDb || {});
  for (let i = 0; i < keys.length; i += 1) {
    const classKey = keys[i];
    const list = SkillMasterDb[classKey];
    if (!Array.isArray(list)) {
      continue;
    }
    const byName = {};
    for (let j = 0; j < list.length; j += 1) {
      const row = list[j];
      if (!row || typeof row !== "object") {
        continue;
      }
      const rawName = typeof row.name === "string" ? row.name : "";
      const baseName =
        typeof normalizeSkillName === "function" ? normalizeSkillName(rawName) : rawName;
      const key = String(baseName || "").trim().toLowerCase();
      if (!key) {
        continue;
      }
      const tags = Array.isArray(row.tags) ? row.tags.map((t) => String(t).toLowerCase()) : [];
      const desc = typeof row.description === "string" ? row.description : "";
      const params = row.params && typeof row.params === "object" ? row.params : {};
      const effects = typeof parseSkillEffects === "function" ? parseSkillEffects(desc) : [];
      const entry = {
        classKey: classKey,
        nameRaw: rawName,
        name: String(baseName || "").trim(),
        tags: tags,
        description: desc,
        params: params,
        effects: effects,
        conception: typeof inferSkillConception === "function"
          ? inferSkillConception({
            tags: tags,
            description: desc,
            range: params.Range || null,
            castTimeSec: null,
            paramsRaw: null,
            effects: effects
          })
          : null
      };
      byName[key] = entry;
    }
    byClass[classKey] = byName;
  }
  return byClass;
}

const SkillMasterIndex = buildSkillMasterIndex();

function getSkillMasterEntry(classKey, rawOrBaseName) {
  if (!classKey) {
    return null;
  }
  const byName = SkillMasterIndex[String(classKey)] || null;
  if (!byName) {
    return null;
  }
  const base =
    typeof normalizeSkillName === "function"
      ? normalizeSkillName(String(rawOrBaseName || ""))
      : String(rawOrBaseName || "");
  const key = base.trim().toLowerCase();
  if (!key) {
    return null;
  }
  return byName[key] || null;
}

function getSkillMasterConception(classKey, rawOrBaseName) {
  const e = getSkillMasterEntry(classKey, rawOrBaseName);
  return e ? e.conception : null;
}
`;
  fs.writeFileSync(skillMasterModuleFile, skillMasterContent, 'utf8');
} else {
  const skillMasterStub = `// AUTO-GENERATED by build.mjs -- do not edit by hand. Regenerated on every build.
const SkillMasterDb = {};
const SkillMasterIndex = {};
function getSkillMasterEntry(classKey, rawOrBaseName) { return null; }
function getSkillMasterConception(classKey, rawOrBaseName) { return null; }
`;
  fs.writeFileSync(skillMasterModuleFile, skillMasterStub, 'utf8');
}

// 5. Concatenate modules sorted alphabetically by filename
const files = fs.readdirSync(modulesDir)
  .filter(f => f.endsWith('.js'))
  .sort((a, b) => a.localeCompare(b));

if (files.length === 0) {
  console.log(`Warning: No module files found in ${modulesDir}`);
}

const parts = [];
for (const f of files) {
  let text = fs.readFileSync(path.join(modulesDir, f), 'utf8');
  text = text.trimEnd() + '\n';
  parts.push(text);
}

let bundle = parts.join('');

// Keep the final Tampermonkey metadata synchronized with version.json.
// 00-header.js is intentionally static source; build artifacts must carry the active version
// so Tampermonkey and the in-game GUI show the same patch identity.
bundle = bundle.replace(/(\/\/ @version\s+)\S+/, `$1${activeVersion}`);
bundle = bundle.replace(/(\/\/ @description\s+).*/, `$1${activeDescription}`);

fs.writeFileSync(bundleFile, bundle, 'utf8');

const loaderFile = path.join(__dirname, 'loader.user.js');
const loaderContent = `// ==UserScript==
// @name         Rebuilt Ligmar Bot Loader
// @namespace    http://tampermonkey.net/
// @version      ${activeVersion}
// @description  Loader stub pointing to local rebuilt bundle
// @match        *://ligmar.io/game/*
// @grant        none
// @require      file:///home/user/rebuilt_src/rebuilt_bot.user.js
// ==UserScript==
`;
fs.writeFileSync(loaderFile, loaderContent, 'utf8');

const bytes = fs.statSync(bundleFile).size;
console.log(`\nBuilt ${bundleFile}`);
console.log(`  version:     v${activeVersion}`);
console.log(`  description: ${activeDescription}`);
console.log(`  bundle size: ${bytes} bytes from ${files.length} modules`);
for (const f of files) {
  console.log(`    + ${f}`);
}
console.log('\nLoader updated successfully.');
