// ==UserScript==
// @name         Ligmar Bot
// @namespace    http://tampermonkey.net/
// @version      0.1.0
// @description  Ligmar.io farming bot foundation
// @author       Victor
// @match        https://ligmar.io/game/*
// @grant        none
// ==/UserScript==

// >>> AUTO-GENERATED by bot/build.ps1 — edit files in bot/modules/, not this file. <<<

(function () {
  "use strict";
