  // AUTO-GENERATED by bot/build.ps1 -- do not edit by hand. Regenerated on every build.
  const BotVersion = {
    version: "0.3.60",
    description: "headline: TEST runs scan hero planner checks SUMMARY",
    builtAt: "2026-05-10T19:02:11.0128278+03:00"
  };
