  // AUTO-GENERATED by bot/build.ps1 -- do not edit by hand. Regenerated on every build.
  const BotVersion = {
    version: "0.3.165",
    description: "TEST: open export in new tab + auto clipboard copy",
    builtAt: "2026-05-13T11:48:16.0858673+03:00"
  };
