  // AUTO-GENERATED by bot/build.ps1 -- do not edit by hand. Regenerated on every build.
  const BotVersion = {
    version: "0.3.173",
    description: "Remove canvas2d miss hook; keep DOM miss_text observe + DB merge",
    builtAt: "2026-05-13T13:10:09.0584055+03:00"
  };
