# build.ps1 — Bumps version, regenerates bot/modules/05-version.js + bot/loader.user.js,
# then concatenates bot/modules/*.js (sorted by filename) into bot/bot.user.js.
#
# Usage:
#   .\bot\build.ps1 -Description "short summary of what changed"   # bump + rebuild (normal flow)
#   .\bot\build.ps1 -NoBump                                        # rebuild only, no version bump
#
# After every successful build, refresh the ligmar.io game tab in the browser. Tampermonkey
# re-fetches the local bundle because the loader's @version changed.

param(
    [string]$Description = "",
    [switch]$NoBump
)

$ErrorActionPreference = "Stop"

$here = Split-Path -Parent $MyInvocation.MyCommand.Path
$modulesDir = Join-Path $here "modules"
$versionFile = Join-Path $here "version.json"
$loaderFile = Join-Path $here "loader.user.js"
$bundleFile = Join-Path $here "bot.user.js"
$versionModuleFile = Join-Path $modulesDir "05-version.js"

if (-not (Test-Path $modulesDir)) {
    throw "Module directory not found: $modulesDir"
}

$utf8NoBom = New-Object System.Text.UTF8Encoding $false

# --- Load version state -----------------------------------------------------
if (-not (Test-Path $versionFile)) {
    throw "version.json not found at $versionFile. Cannot determine bot version."
}
$rawJson = [System.IO.File]::ReadAllText($versionFile, $utf8NoBom)
$versionState = $rawJson | ConvertFrom-Json

# Normalize history to an array even if json has 0/1 entries (PowerShell quirk).
if ($null -eq $versionState.history) {
    $historyList = @()
} else {
    $historyList = @($versionState.history)
}

# --- Bump version (unless -NoBump) ------------------------------------------
if (-not $NoBump) {
    if ([string]::IsNullOrWhiteSpace($Description)) {
        throw "Description is required for a version bump. Use: .\bot\build.ps1 -Description 'short summary'  OR  .\bot\build.ps1 -NoBump"
    }

    $parts = $versionState.version -split '\.'
    if ($parts.Count -ne 3) {
        throw "version.json 'version' must be MAJOR.MINOR.PATCH; got '$($versionState.version)'"
    }
    $major = [int]$parts[0]
    $minor = [int]$parts[1]
    $patch = [int]$parts[2] + 1
    $newVersion = "$major.$minor.$patch"

    $now = (Get-Date).ToString("o")

    $entry = [PSCustomObject]@{
        version     = $newVersion
        description = $Description
        date        = $now
    }

    # Prepend new entry, cap history at 50.
    $historyList = @($entry) + $historyList
    if ($historyList.Count -gt 50) {
        $historyList = $historyList[0..49]
    }

    $versionState = [PSCustomObject]@{
        version     = $newVersion
        description = $Description
        builtAt     = $now
        history     = $historyList
    }

    $versionState | ConvertTo-Json -Depth 20 | Out-File -FilePath $versionFile -Encoding utf8 -NoNewline
}

$activeVersion = $versionState.version
$activeDescription = $versionState.description
$activeBuiltAt = $versionState.builtAt

# --- Regenerate bot/modules/05-version.js ----------------------------------
# Use ConvertTo-Json to safely escape strings with quotes / backslashes / unicode.
$descJs = ($activeDescription | ConvertTo-Json -Compress)
$versionJs = ($activeVersion | ConvertTo-Json -Compress)
$builtAtJs = ($activeBuiltAt | ConvertTo-Json -Compress)

$versionModuleContent = @"
  // AUTO-GENERATED by bot/build.ps1 -- do not edit by hand. Regenerated on every build.
  const BotVersion = {
    version: $versionJs,
    description: $descJs,
    builtAt: $builtAtJs
  };
"@
[System.IO.File]::WriteAllText($versionModuleFile, $versionModuleContent + "`n", $utf8NoBom)

# --- Generate embedded skill master DB module (from tree export JSON) --------
# AI CHANGED: Canonical skill DB: bot/data/ligmar_hero_skills_db.json (fallback: bot/ligmar_hero_skills_db.json).
# The bot ignores Requirements entirely; this generator strips nothing here (file is already cleaned),
# and emits a runtime lookup keyed by classKey + normalizeSkillName (level-invariant).
$skillDbFile = Join-Path $here "data/ligmar_hero_skills_db.json"
if (-not (Test-Path $skillDbFile)) {
    $skillDbFile = Join-Path $here "ligmar_hero_skills_db.json"
}
$skillMasterModuleFile = Join-Path $modulesDir "87-skill-master.generated.js"
if (Test-Path $skillDbFile) {
    $skillDbRaw = [System.IO.File]::ReadAllText($skillDbFile, $utf8NoBom)
    # ConvertTo-Json on a string gives us a JS-safe quoted string literal (escapes quotes/backslashes/newlines).
    $skillDbRawJs = ($skillDbRaw | ConvertTo-Json -Compress)
    $skillMasterContent = @"
  // AUTO-GENERATED by bot/build.ps1 -- do not edit by hand. Regenerated on every build.
  // AI CHANGED: Embedded master hero skill DB (tree export) without Requirements.
  // Provides getSkillMasterEntry(classKey, rawOrBaseName) and getSkillMasterConception(...).
  const SkillMasterDb = JSON.parse($skillDbRawJs);

  function buildSkillMasterIndex() {
    const byClass = {};
    const keys = Object.keys(SkillMasterDb || {});
    for (let i = 0; i < keys.length; i += 1) {
      const classKey = keys[i];
      const list = SkillMasterDb[classKey];
      if (!Array.isArray(list)) {
        continue;
      }
      const byName = {};
      for (let j = 0; j < list.length; j += 1) {
        const row = list[j];
        if (!row || typeof row !== "object") {
          continue;
        }
        const rawName = typeof row.name === "string" ? row.name : "";
        const baseName =
          typeof normalizeSkillName === "function" ? normalizeSkillName(rawName) : rawName;
        const key = String(baseName || "").trim().toLowerCase();
        if (!key) {
          continue;
        }
        const tags = Array.isArray(row.tags) ? row.tags.map((t) => String(t).toLowerCase()) : [];
        const desc = typeof row.description === "string" ? row.description : "";
        const params = row.params && typeof row.params === "object" ? row.params : {};
        const effects = typeof parseSkillEffects === "function" ? parseSkillEffects(desc) : [];
        const entry = {
          classKey: classKey,
          nameRaw: rawName,
          name: String(baseName || "").trim(),
          tags: tags,
          description: desc,
          params: params,
          effects: effects,
          conception: typeof inferSkillConception === "function"
            ? inferSkillConception({
              tags: tags,
              description: desc,
              range: params.Range || null,
              castTimeSec: null,
              paramsRaw: null,
              effects: effects
            })
            : null
        };
        byName[key] = entry;
      }
      byClass[classKey] = byName;
    }
    return byClass;
  }

  const SkillMasterIndex = buildSkillMasterIndex();

  function getSkillMasterEntry(classKey, rawOrBaseName) {
    if (!classKey) {
      return null;
    }
    const byName = SkillMasterIndex[String(classKey)] || null;
    if (!byName) {
      return null;
    }
    const base =
      typeof normalizeSkillName === "function"
        ? normalizeSkillName(String(rawOrBaseName || ""))
        : String(rawOrBaseName || "");
    const key = base.trim().toLowerCase();
    if (!key) {
      return null;
    }
    return byName[key] || null;
  }

  function getSkillMasterConception(classKey, rawOrBaseName) {
    const e = getSkillMasterEntry(classKey, rawOrBaseName);
    return e ? e.conception : null;
  }
"@
    [System.IO.File]::WriteAllText($skillMasterModuleFile, $skillMasterContent + "`n", $utf8NoBom)
} else {
    # If the DB is missing, keep an empty stub so the bundle still builds.
    $skillMasterStub = @"
  // AUTO-GENERATED by bot/build.ps1 -- do not edit by hand. Regenerated on every build.
  // AI CHANGED: Skill master DB not present (bot/ligmar_hero_skills_db.json missing).
  const SkillMasterDb = {};
  const SkillMasterIndex = {};
  function getSkillMasterEntry(classKey, rawOrBaseName) { void classKey; void rawOrBaseName; return null; }
  function getSkillMasterConception(classKey, rawOrBaseName) { void classKey; void rawOrBaseName; return null; }
"@
    [System.IO.File]::WriteAllText($skillMasterModuleFile, $skillMasterStub + "`n", $utf8NoBom)
}

# --- Generate support-skill classification (same skill DB JSON; Node tool) ---
$supportClassifyScript = Join-Path $here "tools/generate-support-classification.mjs"
$supportClassifyOut = Join-Path $modulesDir "88-support-classification.generated.js"
$supportClassifyStub = @"
  // AUTO-GENERATED stub - run Node on tools/generate-support-classification.mjs when bot/data/ligmar_hero_skills_db.json is present.
  const SupportSkillClassificationByClass = {};
  function lookupSupportSkillClassificationFromGeneratedDb(classKey, rawOrBaseName) { void classKey; void rawOrBaseName; return null; }
  function listSupportSkillClassificationFromMasterDb(optClassKey) { void optClassKey; return []; }
"@
if ((Test-Path $skillDbFile) -and (Test-Path $supportClassifyScript)) {
    try {
        $nodeExe = (Get-Command node -ErrorAction Stop).Source
        & $nodeExe $supportClassifyScript $skillDbFile $supportClassifyOut
        if ($LASTEXITCODE -ne 0) {
            throw "generate-support-classification.mjs exit $LASTEXITCODE"
        }
    } catch {
        Write-Warning "Support classification generator failed or Node missing: $_ - writing stub 88-support-classification.generated.js"
        [System.IO.File]::WriteAllText($supportClassifyOut, $supportClassifyStub + "`n", $utf8NoBom)
    }
} else {
    [System.IO.File]::WriteAllText($supportClassifyOut, $supportClassifyStub + "`n", $utf8NoBom)
}

# --- Update loader.user.js @version line ------------------------------------
if (Test-Path $loaderFile) {
    $loaderContent = [System.IO.File]::ReadAllText($loaderFile, $utf8NoBom)
    $newLoader = [regex]::Replace(
        $loaderContent,
        '(?m)^(// @version\s+).*$',
        "// @version      $activeVersion"
    )
    [System.IO.File]::WriteAllText($loaderFile, $newLoader, $utf8NoBom)
}

# --- Concatenate modules ----------------------------------------------------
$files = Get-ChildItem -Path $modulesDir -Filter "*.js" -File | Sort-Object Name
if (-not $files -or $files.Count -eq 0) {
    throw "No module files found in $modulesDir"
}

$parts = New-Object System.Collections.Generic.List[string]
foreach ($f in $files) {
    $text = [System.IO.File]::ReadAllText($f.FullName, $utf8NoBom)
    if ($null -eq $text) { $text = "" }
    # Normalize: ensure exactly one trailing newline so concat doesn't smash files together.
    $text = $text.TrimEnd("`r", "`n") + "`n"
    $parts.Add($text)
}

$bundle = [string]::Join("", $parts)
[System.IO.File]::WriteAllText($bundleFile, $bundle, $utf8NoBom)

$bytes = (Get-Item $bundleFile).Length
Write-Host ""
Write-Host "Built $bundleFile"
Write-Host ("  version:     v" + $activeVersion)
Write-Host ("  description: " + $activeDescription)
Write-Host ("  bundle size: $bytes bytes from $($files.Count) modules")
foreach ($f in $files) {
    Write-Host "    + $($f.Name)"
}
Write-Host ""
Write-Host "Refresh the ligmar.io game tab to load the new bundle."
