# build.ps1 — Bumps version, regenerates bot/modules/05-version.js + bot/loader.user.js,
# then concatenates bot/modules/*.js (sorted by filename) into bot/bot.user.js.
#
# Usage:
#   .\bot\build.ps1 -Description "short summary of what changed"   # bump + rebuild (normal flow)
#   .\bot\build.ps1 -NoBump                                        # rebuild only, no version bump
#
# After every successful build, refresh the ligmar.io game tab in the browser. Tampermonkey
# re-fetches the local bundle because the loader's @version changed.

param(
    [string]$Description = "",
    [switch]$NoBump
)

$ErrorActionPreference = "Stop"

$here = Split-Path -Parent $MyInvocation.MyCommand.Path
$modulesDir = Join-Path $here "modules"
$versionFile = Join-Path $here "version.json"
$loaderFile = Join-Path $here "loader.user.js"
$bundleFile = Join-Path $here "bot.user.js"
$versionModuleFile = Join-Path $modulesDir "05-version.js"

if (-not (Test-Path $modulesDir)) {
    throw "Module directory not found: $modulesDir"
}

$utf8NoBom = New-Object System.Text.UTF8Encoding $false

# --- Load version state -----------------------------------------------------
if (-not (Test-Path $versionFile)) {
    throw "version.json not found at $versionFile. Cannot determine bot version."
}
$rawJson = [System.IO.File]::ReadAllText($versionFile, $utf8NoBom)
$versionState = $rawJson | ConvertFrom-Json

# Normalize history to an array even if json has 0/1 entries (PowerShell quirk).
if ($null -eq $versionState.history) {
    $historyList = @()
} else {
    $historyList = @($versionState.history)
}

# --- Bump version (unless -NoBump) ------------------------------------------
if (-not $NoBump) {
    if ([string]::IsNullOrWhiteSpace($Description)) {
        throw "Description is required for a version bump. Use: .\bot\build.ps1 -Description 'short summary'  OR  .\bot\build.ps1 -NoBump"
    }

    $parts = $versionState.version -split '\.'
    if ($parts.Count -ne 3) {
        throw "version.json 'version' must be MAJOR.MINOR.PATCH; got '$($versionState.version)'"
    }
    $major = [int]$parts[0]
    $minor = [int]$parts[1]
    $patch = [int]$parts[2] + 1
    $newVersion = "$major.$minor.$patch"

    $now = (Get-Date).ToString("o")

    $entry = [PSCustomObject]@{
        version     = $newVersion
        description = $Description
        date        = $now
    }

    # Prepend new entry, cap history at 50.
    $historyList = @($entry) + $historyList
    if ($historyList.Count -gt 50) {
        $historyList = $historyList[0..49]
    }

    $versionState = [PSCustomObject]@{
        version     = $newVersion
        description = $Description
        builtAt     = $now
        history     = $historyList
    }

    $versionState | ConvertTo-Json -Depth 20 | Out-File -FilePath $versionFile -Encoding utf8 -NoNewline
}

$activeVersion = $versionState.version
$activeDescription = $versionState.description
$activeBuiltAt = $versionState.builtAt

# --- Regenerate bot/modules/05-version.js ----------------------------------
# Use ConvertTo-Json to safely escape strings with quotes / backslashes / unicode.
$descJs = ($activeDescription | ConvertTo-Json -Compress)
$versionJs = ($activeVersion | ConvertTo-Json -Compress)
$builtAtJs = ($activeBuiltAt | ConvertTo-Json -Compress)

$versionModuleContent = @"
  // AUTO-GENERATED by bot/build.ps1 -- do not edit by hand. Regenerated on every build.
  const BotVersion = {
    version: $versionJs,
    description: $descJs,
    builtAt: $builtAtJs
  };
"@
[System.IO.File]::WriteAllText($versionModuleFile, $versionModuleContent + "`n", $utf8NoBom)

# --- Update loader.user.js @version line ------------------------------------
if (Test-Path $loaderFile) {
    $loaderContent = [System.IO.File]::ReadAllText($loaderFile, $utf8NoBom)
    $newLoader = [regex]::Replace(
        $loaderContent,
        '(?m)^(// @version\s+).*$',
        "// @version      $activeVersion"
    )
    [System.IO.File]::WriteAllText($loaderFile, $newLoader, $utf8NoBom)
}

# --- Concatenate modules ----------------------------------------------------
$files = Get-ChildItem -Path $modulesDir -Filter "*.js" -File | Sort-Object Name
if (-not $files -or $files.Count -eq 0) {
    throw "No module files found in $modulesDir"
}

$parts = New-Object System.Collections.Generic.List[string]
foreach ($f in $files) {
    $text = [System.IO.File]::ReadAllText($f.FullName, $utf8NoBom)
    if ($null -eq $text) { $text = "" }
    # Normalize: ensure exactly one trailing newline so concat doesn't smash files together.
    $text = $text.TrimEnd("`r", "`n") + "`n"
    $parts.Add($text)
}

$bundle = [string]::Join("", $parts)
[System.IO.File]::WriteAllText($bundleFile, $bundle, $utf8NoBom)

$bytes = (Get-Item $bundleFile).Length
Write-Host ""
Write-Host "Built $bundleFile"
Write-Host ("  version:     v" + $activeVersion)
Write-Host ("  description: " + $activeDescription)
Write-Host ("  bundle size: $bytes bytes from $($files.Count) modules")
foreach ($f in $files) {
    Write-Host "    + $($f.Name)"
}
Write-Host ""
Write-Host "Refresh the ligmar.io game tab to load the new bundle."
